[package]
name = "pixels-of-life-web"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
edition = "2018"

[dependencies]
luminance-web-sys = "0.1.1"
luminance-windowing = "0.9.1"
pixels-of-life = "0.1"
